MLE-12387 : Read NT archive file
marklogic/marklogic-spark-connector pull request #201
Opened 2024-03-19 08:23 UTC by anu3990

2024-03-19 08:25 UTC, anu3990 commented on src/test/java/com/marklogic/spark/reader/file/ReadArchiveFileTest.java
> +            assert(hashSet.contains(temp));
This is working and I can also see the doc content along with the corresponding metadata content. The only problem is - the content comes after the metadata content. For example, the first row  has the content for alexander.metadata followed by content in document alexander (from sample-XML.zip)

2024-03-19 13:18 UTC, rjrudin requested changes

2024-03-19 13:18 UTC, rjrudin commented on src/test/java/com/marklogic/spark/reader/file/ReadArchiveFileTest.java
> +            .load("src/test/resources/mlcp-archive-files/sample-XML.zip");
This is loading an MLCP archive, but for MLE-12387, we want to read an NT archive file. Best way to do that is to reuse the test code from `WriteArchiveTest`. Can just copy and paste from there for now - e.g. I did a quick test like this:

```
@BeforeEach
    void beforeEach() {
        TestUtil.insertTwoDocumentsWithAllMetadata(getDatabaseClient());
    }

    @Test
    void test(@TempDir Path tempDir) {
        newSparkSession().read().format(CONNECTOR_IDENTIFIER)
            .option(Options.CLIENT_URI, makeClientUri())
            .option(Options.READ_DOCUMENTS_COLLECTIONS, "collection1")
            .option(Options.READ_DOCUMENTS_CATEGORIES, "content,metadata")
            .load()
            .repartition(1)
            .write().format(CONNECTOR_IDENTIFIER)
            .option(Options.WRITE_FILES_COMPRESSION, "zip")
            .mode(SaveMode.Append)
            .save(tempDir.toFile().getAbsolutePath());

        sparkSession.read().format(CONNECTOR_IDENTIFIER)
            .option(Options.READ_FILES_TYPE, "archive")
            .load(tempDir.toFile().getAbsolutePath())
            .show();
    }
```

2024-03-19 13:18 UTC, rjrudin commented on src/main/java/com/marklogic/spark/reader/file/ArchiveFileReader.java
> +                return ByteArray.concat(content, FileUtil.readBytes(zipInputStream));
We don't want to concat the next entry. Instead, for an NT archive file, each time we read a zip entry, we know that the next entry will be a metadata file. So we want pseudocode like this:

```
byte[] content = readZipEntry
metadataEntry = findNextFileEntry
// Throw error if this doesn't end with ".metadata", which means it's not a valid archive file. 
byte[] metadata = readZipEntry
// Make an InternalRow using the content data and the metadata.
```

You can use `DocumentMetadataHandle.fromBuffer(byte[])` to convert the byte array into a `DocumentMetadataHandle` instance.

2024-03-19 14:20 UTC, rjrudin commented on src/main/java/com/marklogic/spark/reader/file/ArchiveFileReader.java
> +                return ByteArray.concat(content, FileUtil.readBytes(zipInputStream));
I just started the story for reading an MLCP archive, and I think the approach I'm taking in there should be the same as what's needed here. Will share soon.

2024-03-20 19:28 UTC, rjrudin approved these changes
Looks good. We need to add support for "read.archives.categories", which I forgot to put into the story. I'll write up a separate story for that and use it as a chance to resolve the duplication across the two archive file readers.

2024-03-20 19:34 UTC, merged